using System;
using System.Collections.Generic;
using System.Text;

namespace Models.Models
{
   public  class Parametres
    {
        public int No { get; set; }
        public string CodeTaxeTimbre { get; set; }
        public string ArticleTimbre { get; set; }
        public string CodeTaxeTimbreAchat { get; set; }
        public string NumRegCourant { get; set; }
        public string NumRegCourantF { get; set; }
        public int CouleurR { get; set; }
        public int CouleurB { get; set; }
        public int CouleurV { get; set; }
        public string ArticleFraisD { get; set; }
        public int StockNegatif { get; set; }
        public int Precisions { get; set; }
        public int Limit { get; set; }
        public float TxVente1 { get; set; }
        public float TxVente2 { get; set; }
        public float TxVente3 { get; set; }
        public float TxAchat1 { get; set; }
        public float TxAchat2 { get; set; }
        public float TxAchat3 { get; set; }
        public int RegBL { get; set; }
        public int CollabClient { get; set; }
        public string DEVISE { get; set; }
        public int INCFRS { get; set; }
        public int INCCLI { get; set; }
        public string NUMFRS { get; set; }
        public string NUMCLI { get; set; }
        public string REPFAC { get; set; }
        public string REPLIV { get; set; }
        public string REPACHAT { get; set; }
        public string LOGO { get; set; }
        public string PIED1 { get; set; }
        public string PIED2 { get; set; }
        public string PIED3 { get; set; }
        public string REPCMD { get; set; }
        public string REPDEVIS { get; set; }
        public string LIBLIGTXT1 { get; set; }
        public string LIBLIGTXT2 { get; set; }
        public string LIBLIGTXT3 { get; set; }
        public string LIBLIGVAL1 { get; set; }
        public string LIBLIGVAL2 { get; set; }
        public string LIBLIGVAL3 { get; set; }
        public string LIBLIGDAT1 { get; set; }
        public string LIBLIGDAT2 { get; set; }
        public string LIBLIGDAT3 { get; set; }
        public string LIBLIGBOO1 { get; set; }
        public string LIBLIGBOO2 { get; set; }
        public string LIBLIGBOO3 { get; set; }
        public string LIBDOCTXT1 { get; set; }
        public string LIBDOCTXT2 { get; set; }
        public string LIBDOCTXT3 { get; set; }
        public string LIBDOCVAL1 { get; set; }
        public string LIBDOCVAL2 { get; set; }
        public string LIBDOCVAL3 { get; set; }
        public string LIBDOCDAT1 { get; set; }
        public string LIBDOCDAT2 { get; set; }
        public string LIBDOCDAT3 { get; set; }
        public string LIBDOCBOO1 { get; set; }
        public string LIBDOCBOO2 { get; set; }
        public string LIBDOCBOO3 { get; set; }
        public string LIBCTETXT1 { get; set; }
        public string LIBCTETXT2 { get; set; }
        public string LIBCTETXT3 { get; set; }
        public string LIBCTEVAL1 { get; set; }
        public string LIBCTEVAL2 { get; set; }
        public string LIBCTEVAL3 { get; set; }
        public string LIBCTEDAT1 { get; set; }
        public string LIBCTEDAT2 { get; set; }
        public string LIBCTEDAT3 { get; set; }
        public string LIBCTEBOO1 { get; set; }
        public string LIBCTEBOO2 { get; set; }
        public string LIBCTEBOO3 { get; set; }
        public string REPCMDACH { get; set; }
        public string REPLIVACH { get; set; }
        public string UNITE { get; set; }
        public string LIBARTTXT1 { get; set; }
        public string LIBARTTXT2 { get; set; }
        public string LIBARTTXT3 { get; set; }
        public string LIBARTVAL1 { get; set; }
        public string LIBARTVAL2 { get; set; }
        public string LIBARTVAL3 { get; set; }
        public string LIBARTDAT1 { get; set; }
        public string LIBARTDAT2 { get; set; }
        public string LIBARTDAT3 { get; set; }
        public string LIBARTBOO1 { get; set; }
        public string LIBARTBOO2 { get; set; }
        public string LIBARTBOO3 { get; set; }
        public string PARTAGEPATH { get; set; }
        public string FRAISPRI1 { get; set; }
        public string FRAISPRI2 { get; set; }
        public int TYPEFRAISPRI1 { get; set; }
        public int TYPEFRAISPRI2 { get; set; }
        public int TYPEVALPRI { get; set; }
        public string FAMILLEOT { get; set; }
        public int OTLANCEAUTO { get; set; }
        public int PHASELANCEAUTO { get; set; }
        public int OTSOLDEAUTO { get; set; }
        public int PHASELANCETOUT { get; set; }
        public string LIBOTTXT1 { get; set; }
        public string LIBOTTXT2 { get; set; }
        public string LIBOTTXT3 { get; set; }
        public string LIBOTVAL1 { get; set; }
        public string LIBOTVAL2 { get; set; }
        public string LIBOTVAL3 { get; set; }
        public string LIBOTDAT1 { get; set; }
        public string LIBOTDAT2 { get; set; }
        public string LIBOTDAT3 { get; set; }
        public string LIBOTBOO1 { get; set; }
        public string LIBOTBOO2 { get; set; }
        public string LIBOTBOO3 { get; set; }
        public string REPSTOCK { get; set; }
        public int FIFO { get; set; }
        public int INCART { get; set; }
        public int INCARTFAM { get; set; }
        public string NUMART { get; set; }
        public int MULTISUPPART { get; set; }
        public int MULTISUPPCLT { get; set; }
        public int MULTISUPPFRS { get; set; }
        public string LIBARTTAB1 { get; set; }
        public string LIBARTTAB2 { get; set; }
        public string LIBARTTAB3 { get; set; }
        public string LIBCLTTAB1 { get; set; }
        public string LIBCLTTAB2 { get; set; }
        public string LIBCLTTAB3 { get; set; }
        public int TARIFARTGEN { get; set; }
        public string MAILHOST { get; set; }
        public int MAILPORT { get; set; }
        public string MAILUSER { get; set; }
        public string MAILPASS { get; set; }
        public float TxVente4 { get; set; }
        public float TxAchat4 { get; set; }
        public int RemisePied { get; set; }
        public int MES { get; set; }


    }
}
