using Dapper;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Models.Models;
using Repositories.Contracts;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;

namespace Repositories.Implementations
{
    public class ParametresRepository : IParametresRepository
    {
        IConfiguration Configuration { get; }
        public ParametresRepository(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IDbConnection Connection
        {
            get
            {
                return new SqlConnection(Configuration.GetConnectionString("DefaultConnection"));
            }

        }

        public Parametres GetAll()
        {
            var res = new Parametres();
            try
            {
                using (IDbConnection dbConnection = Connection)
                {
                    string sQuery = @"select 
PA_No as No,PA_CodeTaxeTimbre as CodeTaxeTimbre,PA_ArticleTimbre as ArticleTimbre,
PA_CodeTaxeTimbreAchat as CodeTaxeTimbreAchat,PA_NumRegCourant as NumRegCourant,PA_NumRegCourantF as NumRegCourantF,
PA_CouleurR as CouleurR,PA_CouleurB as CouleurB,PA_CouleurV as CouleurV,PA_ArticleFraisD as ArticleFraisD,
PA_StockNegatif as StockNegatif,PA_Precision as Precisions,PA_Limit as Limit,PA_TxVente1 as   TxVente1,
PA_TxVente2 as   TxVente2,PA_TxVente3 as   TxVente3,PA_TxAchat1 as   TxAchat1,
PA_TxAchat2 as   TxAchat2,PA_TxAchat3 as   TxAchat3,PA_RegBL as RegBL,
PA_CollabClient as CollabClient,PA_DEVISE as DEVISE,PA_INCFRS as INCFRS,PA_INCCLI as INCCLI,PA_NUMFRS as NUMFRS,
PA_NUMCLI as NUMCLI,PA_REPFAC as REPFAC,PA_REPLIV as REPLIV,PA_REPACHAT as REPACHAT,PA_LOGO as LOGO,
PA_PIED1 as PIED1,PA_PIED2 as PIED2,PA_PIED3 as PIED3,PA_REPCMD as REPCMD,PA_REPDEVIS as REPDEVIS,
PA_LIBLIGTXT1 as LIBLIGTXT1,PA_LIBLIGTXT2 as LIBLIGTXT2,PA_LIBLIGTXT3 as LIBLIGTXT3,PA_LIBLIGVAL1 as LIBLIGVAL1,
PA_LIBLIGVAL2 as LIBLIGVAL2,PA_LIBLIGVAL3 as LIBLIGVAL3,PA_LIBLIGDAT1 as LIBLIGDAT1,PA_LIBLIGDAT2 as LIBLIGDAT2,
PA_LIBLIGDAT3 as LIBLIGDAT3,PA_LIBLIGBOO1 as LIBLIGBOO1,PA_LIBLIGBOO2 as LIBLIGBOO2,PA_LIBLIGBOO3 as LIBLIGBOO3,
PA_LIBDOCTXT1 as LIBDOCTXT1,PA_LIBDOCTXT2 as LIBDOCTXT2,PA_LIBDOCTXT3 as LIBDOCTXT3,PA_LIBDOCVAL1 as LIBDOCVAL1,
PA_LIBDOCVAL2 as LIBDOCVAL2,PA_LIBDOCVAL3 as LIBDOCVAL3,PA_LIBDOCDAT1 as LIBDOCDAT1,PA_LIBDOCDAT2 as LIBDOCDAT2,
PA_LIBDOCDAT3 as LIBDOCDAT3,PA_LIBDOCBOO1 as LIBDOCBOO1,PA_LIBDOCBOO2 as LIBDOCBOO2,PA_LIBDOCBOO3 as LIBDOCBOO3,
PA_LIBCTETXT1 as LIBCTETXT1,PA_LIBCTETXT2 as LIBCTETXT2,PA_LIBCTETXT3 as LIBCTETXT3,PA_LIBCTEVAL1 as LIBCTEVAL1,
PA_LIBCTEVAL2 as LIBCTEVAL2,PA_LIBCTEVAL3 as LIBCTEVAL3,PA_LIBCTEDAT1 as LIBCTEDAT1,PA_LIBCTEDAT2 as LIBCTEDAT2,
PA_LIBCTEDAT3 as LIBCTEDAT3,PA_LIBCTEBOO1 as LIBCTEBOO1,PA_LIBCTEBOO2 as LIBCTEBOO2,PA_LIBCTEBOO3 as LIBCTEBOO3,
PA_REPCMDACH as REPCMDACH,PA_REPLIVACH as REPLIVACH,PA_UNITE as UNITE,PA_LIBARTTXT1 as LIBARTTXT1,
PA_LIBARTTXT2 as LIBARTTXT2,PA_LIBARTTXT3 as LIBARTTXT3,PA_LIBARTVAL1 as LIBARTVAL1,PA_LIBARTVAL2 as LIBARTVAL2,
PA_LIBARTVAL3 as LIBARTVAL3,PA_LIBARTDAT1 as LIBARTDAT1,PA_LIBARTDAT2 as LIBARTDAT2,PA_LIBARTDAT3 as LIBARTDAT3,
PA_LIBARTBOO1 as LIBARTBOO1,PA_LIBARTBOO2 as LIBARTBOO2,PA_LIBARTBOO3 as LIBARTBOO3,PA_PARTAGEPATH as PARTAGEPATH,
PA_FRAISPRI1 as FRAISPRI1,PA_FRAISPRI2 as FRAISPRI2,PA_TYPEFRAISPRI1 as TYPEFRAISPRI1,PA_TYPEFRAISPRI2 as TYPEFRAISPRI2,
PA_TYPEVALPRI as TYPEVALPRI,PA_FAMILLEOT as FAMILLEOT,PA_OTLANCEAUTO as OTLANCEAUTO,PA_PHASELANCEAUTO as PHASELANCEAUTO,
PA_OTSOLDEAUTO as OTSOLDEAUTO,PA_PHASELANCETOUT as PHASELANCETOUT,PA_LIBOTTXT1 as LIBOTTXT1,
PA_LIBOTTXT2 as LIBOTTXT2,PA_LIBOTTXT3 as LIBOTTXT3,PA_LIBOTVAL1 as LIBOTVAL1,PA_LIBOTVAL2 as LIBOTVAL2,PA_LIBOTVAL3 as LIBOTVAL3,
PA_LIBOTDAT1 as LIBOTDAT1,PA_LIBOTDAT2 as LIBOTDAT2,PA_LIBOTDAT3 as LIBOTDAT3,PA_LIBOTBOO1 as LIBOTBOO1,
PA_LIBOTBOO2 as LIBOTBOO2,PA_LIBOTBOO3 as LIBOTBOO3,PA_REPSTOCK as REPSTOCK,PA_FIFO as FIFO,PA_INCART as INCART,
PA_INCARTFAM as INCARTFAM,PA_NUMART as NUMART,PA_MULTISUPPART as MULTISUPPART,PA_MULTISUPPCLT as MULTISUPPCLT,
PA_MULTISUPPFRS as MULTISUPPFRS,PA_LIBARTTAB1 as LIBARTTAB1,PA_LIBARTTAB2 as LIBARTTAB2,PA_LIBARTTAB3 as LIBARTTAB3,
PA_LIBCLTTAB1 as LIBCLTTAB1,PA_LIBCLTTAB2 as LIBCLTTAB2,PA_LIBCLTTAB3 as LIBCLTTAB3,PA_TARIFARTGEN as TARIFARTGEN,
PA_MAILHOST as MAILHOST,PA_MAILPORT as MAILPORT,PA_MAILUSER as MAILUSER,PA_MAILPASS as MAILPASS,
PA_TxVente4 as  TxVente4,PA_TxAchat4 as  TxAchat4,PA_RemisePied as RemisePied,PA_MES as MES
from P_PARAMETRE  ";
                    dbConnection.Open();
                    res = dbConnection.Query<Parametres>(sQuery).FirstOrDefault();

                }

            }
            catch (Exception)
            {

                return null;
            }

            return res;
        }
       
       

        public Parametres Update(Parametres parametres)
        {

            try
            {
                using (IDbConnection dbConnection = Connection)
                {
                    string sQuery = @"update P_PARAMETRE set 
                          PA_No=@No,PA_CodeTaxeTimbre=@CodeTaxeTimbre,PA_ArticleTimbre=@ArticleTimbre,PA_CodeTaxeTimbreAchat=@CodeTaxeTimbreAchat,
PA_NumRegCourant=@NumRegCourant,PA_NumRegCourantF=@NumRegCourantF,PA_CouleurR=@CouleurR,PA_CouleurB=@CouleurB,PA_CouleurV=@CouleurV,
PA_ArticleFraisD=@ArticleFraisD,PA_StockNegatif=@StockNegatif,PA_Precision=@Precisions,PA_Limit=@Limit,PA_TxVente1=@  TxVente1,
PA_TxVente2=@TxVente2,PA_TxVente3=@TxVente3,PA_TxAchat1=@TxAchat1,PA_TxAchat2=@TxAchat2,
PA_TxAchat3=@TxAchat3,PA_RegBL=@RegBL,PA_CollabClient=@CollabClient,PA_DEVISE=@DEVISE,PA_INCFRS=@INCFRS,
PA_INCCLI=@INCCLI,PA_NUMFRS=@NUMFRS,PA_NUMCLI=@NUMCLI,PA_REPFAC=@REPFAC,PA_REPLIV=@REPLIV,PA_REPACHAT=@REPACHAT,
PA_LOGO=@LOGO,PA_PIED1=@PIED1,PA_PIED2=@PIED2,PA_PIED3=@PIED3,PA_REPCMD=@REPCMD,PA_REPDEVIS=@REPDEVIS,
PA_LIBLIGTXT1=@LIBLIGTXT1,PA_LIBLIGTXT2=@LIBLIGTXT2,PA_LIBLIGTXT3=@LIBLIGTXT3,PA_LIBLIGVAL1=@LIBLIGVAL1,
PA_LIBLIGVAL2=@LIBLIGVAL2,PA_LIBLIGVAL3=@LIBLIGVAL3,PA_LIBLIGDAT1=@LIBLIGDAT1,PA_LIBLIGDAT2=@LIBLIGDAT2,
PA_LIBLIGDAT3=@LIBLIGDAT3,PA_LIBLIGBOO1=@LIBLIGBOO1,PA_LIBLIGBOO2=@LIBLIGBOO2,PA_LIBLIGBOO3=@LIBLIGBOO3,
PA_LIBDOCTXT1=@LIBDOCTXT1,PA_LIBDOCTXT2=@LIBDOCTXT2,PA_LIBDOCTXT3=@LIBDOCTXT3,PA_LIBDOCVAL1=@LIBDOCVAL1,
PA_LIBDOCVAL2=@LIBDOCVAL2,PA_LIBDOCVAL3=@LIBDOCVAL3,PA_LIBDOCDAT1=@LIBDOCDAT1,PA_LIBDOCDAT2=@LIBDOCDAT2,
PA_LIBDOCDAT3=@LIBDOCDAT3,PA_LIBDOCBOO1=@LIBDOCBOO1,PA_LIBDOCBOO2=@LIBDOCBOO2,PA_LIBDOCBOO3=@LIBDOCBOO3,
PA_LIBCTETXT1=@LIBCTETXT1,PA_LIBCTETXT2=@LIBCTETXT2,PA_LIBCTETXT3=@LIBCTETXT3,PA_LIBCTEVAL1=@LIBCTEVAL1,
PA_LIBCTEVAL2=@LIBCTEVAL2,PA_LIBCTEVAL3=@LIBCTEVAL3,PA_LIBCTEDAT1=@LIBCTEDAT1,PA_LIBCTEDAT2=@LIBCTEDAT2,
PA_LIBCTEDAT3=@LIBCTEDAT3,PA_LIBCTEBOO1=@LIBCTEBOO1,PA_LIBCTEBOO2=@LIBCTEBOO2,PA_LIBCTEBOO3=@LIBCTEBOO3,
PA_REPCMDACH=@REPCMDACH,PA_REPLIVACH=@REPLIVACH,PA_UNITE=@UNITE,PA_LIBARTTXT1=@LIBARTTXT1,PA_LIBARTTXT2=@LIBARTTXT2,
PA_LIBARTTXT3=@LIBARTTXT3,PA_LIBARTVAL1=@LIBARTVAL1,PA_LIBARTVAL2=@LIBARTVAL2,PA_LIBARTVAL3=@LIBARTVAL3,
PA_LIBARTDAT1=@LIBARTDAT1,PA_LIBARTDAT2=@LIBARTDAT2,PA_LIBARTDAT3=@LIBARTDAT3,PA_LIBARTBOO1=@LIBARTBOO1,
PA_LIBARTBOO2=@LIBARTBOO2,PA_LIBARTBOO3=@LIBARTBOO3,PA_PARTAGEPATH=@PARTAGEPATH,PA_FRAISPRI1=@FRAISPRI1,
PA_FRAISPRI2=@FRAISPRI2,PA_TYPEFRAISPRI1=@TYPEFRAISPRI1,PA_TYPEFRAISPRI2=@TYPEFRAISPRI2,
PA_TYPEVALPRI=@TYPEVALPRI,PA_FAMILLEOT=@FAMILLEOT,PA_OTLANCEAUTO=@OTLANCEAUTO,PA_PHASELANCEAUTO=@PHASELANCEAUTO,
PA_OTSOLDEAUTO=@OTSOLDEAUTO,PA_PHASELANCETOUT=@PHASELANCETOUT,PA_LIBOTTXT1=@LIBOTTXT1,
PA_LIBOTTXT2=@LIBOTTXT2,PA_LIBOTTXT3=@LIBOTTXT3,PA_LIBOTVAL1=@LIBOTVAL1,PA_LIBOTVAL2=@LIBOTVAL2,
PA_LIBOTVAL3=@LIBOTVAL3,PA_LIBOTDAT1=@LIBOTDAT1,PA_LIBOTDAT2=@LIBOTDAT2,PA_LIBOTDAT3=@LIBOTDAT3,
PA_LIBOTBOO1=@LIBOTBOO1,PA_LIBOTBOO2=@LIBOTBOO2,PA_LIBOTBOO3=@LIBOTBOO3,PA_REPSTOCK=@REPSTOCK,PA_FIFO=@FIFO,
PA_INCART=@INCART,PA_INCARTFAM=@INCARTFAM,PA_NUMART=@NUMART,PA_MULTISUPPART=@MULTISUPPART,PA_MULTISUPPCLT=@MULTISUPPCLT,
PA_MULTISUPPFRS=@MULTISUPPFRS,PA_LIBARTTAB1=@LIBARTTAB1,PA_LIBARTTAB2=@LIBARTTAB2,PA_LIBARTTAB3=@LIBARTTAB3,
PA_LIBCLTTAB1=@LIBCLTTAB1,PA_LIBCLTTAB2=@LIBCLTTAB2,PA_LIBCLTTAB3=@LIBCLTTAB3,PA_TARIFARTGEN=@TARIFARTGEN,
PA_MAILHOST=@MAILHOST,PA_MAILPORT=@MAILPORT,PA_MAILUSER=@MAILUSER,PA_MAILPASS=@MAILPASS,PA_TxVente4=@  TxVente4,
PA_TxAchat4=@  TxAchat4,PA_RemisePied=@RemisePied,PA_MES=@MES
 ";
                    dbConnection.Open();
                    dbConnection.Execute(sQuery, parametres);
                }

            }
            catch (Exception)
            {
                return null;

            }
            return parametres;
        }


        public bool UpdateNUMCLI(string numcli)
        {
            try
            {
                using (IDbConnection dbConnection = Connection)
                {
                    string sQuery = @"update P_PARAMETRE set 
                          PA_NUMCLI=@NUMCLI ";
                    dbConnection.Open();
                    dbConnection.Execute(sQuery, numcli);
                }
              
            }
            catch (Exception)
            {
                return false;

            }
            return true;
        }


    }
}
